server:
  port: 8181
spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://192.168.31.250:3306/cloudstudy?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#配置mybatis-plus信息
mybatis-plus:
  #  global-config:
  #    db-config:
  #       id生成策略 auto为数据库自增
  #     id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml

security:
  oauth2:
    client:
      #不多说了
      client-id: web
      client-secret: 654321
      #Token获取地址
      access-token-uri: http://localhost:8500/sso/oauth/token
      #验证页面地址
      user-authorization-uri: http://localhost:8500/sso/oauth/authorize
    resource:
      #Token信息获取和校验地址
      token-info-uri: http://localhost:8500/sso/oauth/check_token
